fix localstorage not defined (#410)
ReferenceError: localStorage is not defined
    at 21522 (.next/server/chunks/4670.js:1:26106)
    at c (.next/server/webpack-runtime.js:1:190)
    at 35743 (.next/server/chunks/4670.js:10:89054)
    at c (.next/server/webpack-runtime.js:1:190)
    at 80964 (.next/server/chunks/4670.js:10:327089)
    at Object.c [as require] (.next/server/webpack-runtime.js:1:190) {
  digest: '2014840790'
}